--------------------------------------------------------
--  DDL for Sequence SEQCRMLOGS
--------------------------------------------------------

   CREATE SEQUENCE  "COMERCIAL"."SEQCRMLOGS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Table CRM_LOGS
--------------------------------------------------------

  CREATE TABLE "COMERCIAL"."CRM_LOGS"
   (	"ID" NUMBER(16,0),
	"FECHA" DATE,
	"DESCRIPTION" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COMERCIAL" ;
--------------------------------------------------------
--  DDL for Index C2C_SYNCS_INDEX1
--------------------------------------------------------

  CREATE INDEX "COMERCIAL"."CRM_LOGS_INDEX1" ON "COMERCIAL"."CRM_LOGS" ("ID" DESC)
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COMERCIAL" ;
--------------------------------------------------------
--  Constraints for Table C2C_SYNCS
--------------------------------------------------------

  ALTER TABLE "COMERCIAL"."CRM_LOGS" MODIFY ("ID" NOT NULL ENABLE);
